### ISSUE TITLE
Look into numerous recompositions in screens

### ISSUE THREAD

**Issue by darkvoid32** [thunderbiscuit/devkit-wallet#19]

**Comment by yellowHatpro** [comment]
Is this wallet still under active maintenance, or is the focus on Padawan??? 🤔

**Comment by thunderbiscuit** [comment]
This wallet is being actively maintained for sure. It needs updating to the latest bdk-android, and I'd love to add some of the new features we exposed in the latest releases.

**Comment by yellowHatpro** [comment]
Alright, I would try to contribute to this repo as well. 
Just a quick question, are the advanced features mentioned in this project the ones we want to add in Padawan as well?

**Comment by thunderbiscuit** [comment]
No totally different features. Padawan is at the moment close to its feature-set for the 1.0 release. The Devkit Wallet advanced-features version of the app, however, can basically just add anything that's available in [bdk-android](https://bitcoindevkit.org/android/).

**Comment by yellowHatpro** [comment]
Hi, I was trying to build advanced-features branch, but the app crashes everytime with this error:
 ```  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.goldenraven.devkitwallet/com.goldenraven.devkitwallet.DevkitWalletActivity}: org.bitcoindevkit.BdkException$Descriptor: Descriptor(Miniscript(Unexpected("(0 args) while parsing Miniscript")))

Caused by: org.bitcoindevkit.BdkException$Descriptor: Descriptor(Miniscript(Unexpected("(0 args) while parsing Miniscript")))`
``` 

I remember in this conversation, you mentioned some incompatibility of rust v 1.68 and Miniscript https://github.com/bitcoindevkit/bdk-ffi/pull/336#issuecomment-1526323175 
Could it be the reason of build failure??

**Comment by yellowHatpro** [comment]
Hi, are we able to build the advanced-features branch ?
I am getting an error in the beginning itself:
```
    Caused by: org.bitcoindevkit.BdkException$Descriptor: Descriptor(Miniscript(Unexpected("(0 args) while parsing Miniscript")))
                      	at org.bitcoindevkit.BdkException$ErrorHandler.read(bdk.kt:1863)
                      	at org.bitcoindevkit.BdkException$ErrorHandler$lift$1.invoke(bdk.kt:1831)
                      	at org.bitcoindevkit.BdkException$ErrorHandler$lift$1.invoke(bdk.kt:1831)
                      	at org.bitcoindevkit.BdkKt.liftFromRustBuffer(bdk.kt:209)
                      	at org.bitcoindevkit.BdkException$ErrorHandler.lift(bdk.kt:1831)
                      	at org.bitcoindevkit.BdkException$ErrorHandler.lift(bdk.kt:1829)
                      	at org.bitcoindevkit.Wallet.<init>(bdk.kt:2235)
                      	at com.goldenraven.devkitwallet.data.Wallet.initialize(Wallet.kt:36)
                      	at com.goldenraven.devkitwallet.data.Wallet.loadExistingWallet(Wallet.kt:82)
                      	at com.goldenraven.devkitwallet.DevkitWalletActivity.onCreate(DevkitWalletActivity.kt:39)
                      	```
                      	
                      	Is it known error?

**Comment by yellowHatpro** [comment]
@thunderbiscuit as mentioned in some previous discussion, i came to know miniscript issue with rust version 1.68, could the above issue be related to rust version?

**Comment by thunderbiscuit** [comment]
No in this case I suspect it's the code creating the wallet that needs updating. The older versions of the library did not have descriptor templates, and there are a few new types related to keys and descriptors in the later versions of the library. I don't remember exactly when this was introduced but take a look [at these examples](https://github.com/thunderbiscuit/bitcoindevkit-scripts) for how to build wallets with the Descriptor type. I think the old code might not be valid anymore.

**Comment by yellowHatpro** [comment]
Yeah true I found the bdk library used out of date. On updating the version, the code was breaking. Are we intending to update the advanced wallet, if yes, then till which version number? (Or should we just go latest bdk version😛)

**Comment by thunderbiscuit** [comment]
Let's bring it all the way up to 0.28.0 (the latest release).

**Comment by yellowHatpro** [comment]
Lesgoo!!

**Comment by thunderbiscuit** [comment]
For this particular wallet I'm not too concerned with efficiency of the Compose runtime. Closing this now.
